spring:
  security:
    oauth2:
      resourceserver:
        opaque:
          ## 令牌校验地址
          introspection-uri: http://auth.nobody.com:9002/oauth/check_token
          introspection-client-id: my_client
          introspection-client-secret: 123

server:
  port: 9003