server:
  port: 9001
spring:
  application:
    name: nobody-admin
  datasource:
    url: jdbc:mysql://localhost:3306/demo01?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.weshare.nobody.domain,com.weshare.nobody.entity
